//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APU.Negocio.WS_Gasolutions {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VentaGasolutionsInfo", Namespace="http://schemas.datacontract.org/2004/07/APU.Entidad")]
    [System.SerializableAttribute()]
    public partial class VentaGasolutionsInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal _calculoIgvField;
        
        private string _codigoRespuestaField;
        
        private string _comprobanteImpresoField;
        
        private string _departamentoEmisorField;
        
        private decimal _descuentoField;
        
        private string _direccionEmisorField;
        
        private string _direccionReceptorField;
        
        private string _distritoEmisorField;
        
        private string _estadoField;
        
        private int _estadoIdField;
        
        private int _exitoField;
        
        private System.DateTime _fechaCreacionField;
        
        private System.DateTime _fechaEmisionField;
        
        private decimal _gravadasField;
        
        private string _idDocumentoField;
        
        private string _mensajeErrorField;
        
        private string _mensajeRespuestaField;
        
        private string _monedaField;
        
        private string _monedaIdField;
        
        private string _montoEnLetrasField;
        
        private string _nombreArchivoField;
        
        private string _nombreComercialEmisorField;
        
        private string _nombreComercialReceptorField;
        
        private string _nombreLegalEmisorField;
        
        private string _nombreLegalReceptorField;
        
        private string _nroDocumentoEmisorField;
        
        private string _nroDocumentoReceptorField;
        
        private string _nroTicketField;
        
        private int _numeroFilaField;
        
        private string _placaVehiculoField;
        
        private string _provinciaEmisorField;
        
        private string _simboloMonedaField;
        
        private string _tipoDocumentoField;
        
        private string _tipoDocumentoEmisorField;
        
        private string _tipoDocumentoReceptorField;
        
        private int _totalFilasField;
        
        private decimal _totalIgvField;
        
        private decimal _totalVentaField;
        
        private string _ubigeoEmisorField;
        
        private int _ventaGasolutionsIdField;
        
        private APU.Negocio.WS_Gasolutions.VentaDetalleGasolutionsInfo Itemk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal _calculoIgv {
            get {
                return this._calculoIgvField;
            }
            set {
                if ((this._calculoIgvField.Equals(value) != true)) {
                    this._calculoIgvField = value;
                    this.RaisePropertyChanged("_calculoIgv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _codigoRespuesta {
            get {
                return this._codigoRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this._codigoRespuestaField, value) != true)) {
                    this._codigoRespuestaField = value;
                    this.RaisePropertyChanged("_codigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _comprobanteImpreso {
            get {
                return this._comprobanteImpresoField;
            }
            set {
                if ((object.ReferenceEquals(this._comprobanteImpresoField, value) != true)) {
                    this._comprobanteImpresoField = value;
                    this.RaisePropertyChanged("_comprobanteImpreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _departamentoEmisor {
            get {
                return this._departamentoEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this._departamentoEmisorField, value) != true)) {
                    this._departamentoEmisorField = value;
                    this.RaisePropertyChanged("_departamentoEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal _descuento {
            get {
                return this._descuentoField;
            }
            set {
                if ((this._descuentoField.Equals(value) != true)) {
                    this._descuentoField = value;
                    this.RaisePropertyChanged("_descuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _direccionEmisor {
            get {
                return this._direccionEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this._direccionEmisorField, value) != true)) {
                    this._direccionEmisorField = value;
                    this.RaisePropertyChanged("_direccionEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _direccionReceptor {
            get {
                return this._direccionReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this._direccionReceptorField, value) != true)) {
                    this._direccionReceptorField = value;
                    this.RaisePropertyChanged("_direccionReceptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _distritoEmisor {
            get {
                return this._distritoEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this._distritoEmisorField, value) != true)) {
                    this._distritoEmisorField = value;
                    this.RaisePropertyChanged("_distritoEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _estado {
            get {
                return this._estadoField;
            }
            set {
                if ((object.ReferenceEquals(this._estadoField, value) != true)) {
                    this._estadoField = value;
                    this.RaisePropertyChanged("_estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _estadoId {
            get {
                return this._estadoIdField;
            }
            set {
                if ((this._estadoIdField.Equals(value) != true)) {
                    this._estadoIdField = value;
                    this.RaisePropertyChanged("_estadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _exito {
            get {
                return this._exitoField;
            }
            set {
                if ((this._exitoField.Equals(value) != true)) {
                    this._exitoField = value;
                    this.RaisePropertyChanged("_exito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _fechaCreacion {
            get {
                return this._fechaCreacionField;
            }
            set {
                if ((this._fechaCreacionField.Equals(value) != true)) {
                    this._fechaCreacionField = value;
                    this.RaisePropertyChanged("_fechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _fechaEmision {
            get {
                return this._fechaEmisionField;
            }
            set {
                if ((this._fechaEmisionField.Equals(value) != true)) {
                    this._fechaEmisionField = value;
                    this.RaisePropertyChanged("_fechaEmision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal _gravadas {
            get {
                return this._gravadasField;
            }
            set {
                if ((this._gravadasField.Equals(value) != true)) {
                    this._gravadasField = value;
                    this.RaisePropertyChanged("_gravadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _idDocumento {
            get {
                return this._idDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this._idDocumentoField, value) != true)) {
                    this._idDocumentoField = value;
                    this.RaisePropertyChanged("_idDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _mensajeError {
            get {
                return this._mensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this._mensajeErrorField, value) != true)) {
                    this._mensajeErrorField = value;
                    this.RaisePropertyChanged("_mensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _mensajeRespuesta {
            get {
                return this._mensajeRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this._mensajeRespuestaField, value) != true)) {
                    this._mensajeRespuestaField = value;
                    this.RaisePropertyChanged("_mensajeRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _moneda {
            get {
                return this._monedaField;
            }
            set {
                if ((object.ReferenceEquals(this._monedaField, value) != true)) {
                    this._monedaField = value;
                    this.RaisePropertyChanged("_moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _monedaId {
            get {
                return this._monedaIdField;
            }
            set {
                if ((object.ReferenceEquals(this._monedaIdField, value) != true)) {
                    this._monedaIdField = value;
                    this.RaisePropertyChanged("_monedaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _montoEnLetras {
            get {
                return this._montoEnLetrasField;
            }
            set {
                if ((object.ReferenceEquals(this._montoEnLetrasField, value) != true)) {
                    this._montoEnLetrasField = value;
                    this.RaisePropertyChanged("_montoEnLetras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _nombreArchivo {
            get {
                return this._nombreArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this._nombreArchivoField, value) != true)) {
                    this._nombreArchivoField = value;
                    this.RaisePropertyChanged("_nombreArchivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _nombreComercialEmisor {
            get {
                return this._nombreComercialEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this._nombreComercialEmisorField, value) != true)) {
                    this._nombreComercialEmisorField = value;
                    this.RaisePropertyChanged("_nombreComercialEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _nombreComercialReceptor {
            get {
                return this._nombreComercialReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this._nombreComercialReceptorField, value) != true)) {
                    this._nombreComercialReceptorField = value;
                    this.RaisePropertyChanged("_nombreComercialReceptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _nombreLegalEmisor {
            get {
                return this._nombreLegalEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this._nombreLegalEmisorField, value) != true)) {
                    this._nombreLegalEmisorField = value;
                    this.RaisePropertyChanged("_nombreLegalEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _nombreLegalReceptor {
            get {
                return this._nombreLegalReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this._nombreLegalReceptorField, value) != true)) {
                    this._nombreLegalReceptorField = value;
                    this.RaisePropertyChanged("_nombreLegalReceptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _nroDocumentoEmisor {
            get {
                return this._nroDocumentoEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this._nroDocumentoEmisorField, value) != true)) {
                    this._nroDocumentoEmisorField = value;
                    this.RaisePropertyChanged("_nroDocumentoEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _nroDocumentoReceptor {
            get {
                return this._nroDocumentoReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this._nroDocumentoReceptorField, value) != true)) {
                    this._nroDocumentoReceptorField = value;
                    this.RaisePropertyChanged("_nroDocumentoReceptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _nroTicket {
            get {
                return this._nroTicketField;
            }
            set {
                if ((object.ReferenceEquals(this._nroTicketField, value) != true)) {
                    this._nroTicketField = value;
                    this.RaisePropertyChanged("_nroTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _numeroFila {
            get {
                return this._numeroFilaField;
            }
            set {
                if ((this._numeroFilaField.Equals(value) != true)) {
                    this._numeroFilaField = value;
                    this.RaisePropertyChanged("_numeroFila");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _placaVehiculo {
            get {
                return this._placaVehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this._placaVehiculoField, value) != true)) {
                    this._placaVehiculoField = value;
                    this.RaisePropertyChanged("_placaVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _provinciaEmisor {
            get {
                return this._provinciaEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this._provinciaEmisorField, value) != true)) {
                    this._provinciaEmisorField = value;
                    this.RaisePropertyChanged("_provinciaEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _simboloMoneda {
            get {
                return this._simboloMonedaField;
            }
            set {
                if ((object.ReferenceEquals(this._simboloMonedaField, value) != true)) {
                    this._simboloMonedaField = value;
                    this.RaisePropertyChanged("_simboloMoneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _tipoDocumento {
            get {
                return this._tipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this._tipoDocumentoField, value) != true)) {
                    this._tipoDocumentoField = value;
                    this.RaisePropertyChanged("_tipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _tipoDocumentoEmisor {
            get {
                return this._tipoDocumentoEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this._tipoDocumentoEmisorField, value) != true)) {
                    this._tipoDocumentoEmisorField = value;
                    this.RaisePropertyChanged("_tipoDocumentoEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _tipoDocumentoReceptor {
            get {
                return this._tipoDocumentoReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this._tipoDocumentoReceptorField, value) != true)) {
                    this._tipoDocumentoReceptorField = value;
                    this.RaisePropertyChanged("_tipoDocumentoReceptor");
                }
            }
        }
        


        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _totalFilas {
            get {
                return this._totalFilasField;
            }
            set {
                if ((this._totalFilasField.Equals(value) != true)) {
                    this._totalFilasField = value;
                    this.RaisePropertyChanged("_totalFilas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal _totalIgv {
            get {
                return this._totalIgvField;
            }
            set {
                if ((this._totalIgvField.Equals(value) != true)) {
                    this._totalIgvField = value;
                    this.RaisePropertyChanged("_totalIgv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal _totalVenta {
            get {
                return this._totalVentaField;
            }
            set {
                if ((this._totalVentaField.Equals(value) != true)) {
                    this._totalVentaField = value;
                    this.RaisePropertyChanged("_totalVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ubigeoEmisor {
            get {
                return this._ubigeoEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this._ubigeoEmisorField, value) != true)) {
                    this._ubigeoEmisorField = value;
                    this.RaisePropertyChanged("_ubigeoEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _ventaGasolutionsId {
            get {
                return this._ventaGasolutionsIdField;
            }
            set {
                if ((this._ventaGasolutionsIdField.Equals(value) != true)) {
                    this._ventaGasolutionsIdField = value;
                    this.RaisePropertyChanged("_ventaGasolutionsId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Item>k__BackingField", IsRequired=true)]
        public APU.Negocio.WS_Gasolutions.VentaDetalleGasolutionsInfo Itemk__BackingField {
            get {
                return this.Itemk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Itemk__BackingFieldField, value) != true)) {
                    this.Itemk__BackingFieldField = value;
                    this.RaisePropertyChanged("Itemk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VentaDetalleGasolutionsInfo", Namespace="http://schemas.datacontract.org/2004/07/APU.Entidad")]
    [System.SerializableAttribute()]
    public partial class VentaDetalleGasolutionsInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal _cantidadField;
        
        private string _codigoItemField;
        
        private string _descripcionField;
        
        private System.DateTime _fechaCreacionField;
        
        private int _idField;
        
        private decimal _impuestoField;
        
        private decimal _precioUnitarioField;
        
        private string _tipoImpuestoField;
        
        private string _tipoPrecioField;
        
        private decimal _totalVentaField;
        
        private string _unidadMedidaField;
        
        private int _ventaDetalleGasolutionsIdField;
        
        private int _ventaGasolutionsIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal _cantidad {
            get {
                return this._cantidadField;
            }
            set {
                if ((this._cantidadField.Equals(value) != true)) {
                    this._cantidadField = value;
                    this.RaisePropertyChanged("_cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _codigoItem {
            get {
                return this._codigoItemField;
            }
            set {
                if ((object.ReferenceEquals(this._codigoItemField, value) != true)) {
                    this._codigoItemField = value;
                    this.RaisePropertyChanged("_codigoItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _descripcion {
            get {
                return this._descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this._descripcionField, value) != true)) {
                    this._descripcionField = value;
                    this.RaisePropertyChanged("_descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _fechaCreacion {
            get {
                return this._fechaCreacionField;
            }
            set {
                if ((this._fechaCreacionField.Equals(value) != true)) {
                    this._fechaCreacionField = value;
                    this.RaisePropertyChanged("_fechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal _impuesto {
            get {
                return this._impuestoField;
            }
            set {
                if ((this._impuestoField.Equals(value) != true)) {
                    this._impuestoField = value;
                    this.RaisePropertyChanged("_impuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal _precioUnitario {
            get {
                return this._precioUnitarioField;
            }
            set {
                if ((this._precioUnitarioField.Equals(value) != true)) {
                    this._precioUnitarioField = value;
                    this.RaisePropertyChanged("_precioUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _tipoImpuesto {
            get {
                return this._tipoImpuestoField;
            }
            set {
                if ((object.ReferenceEquals(this._tipoImpuestoField, value) != true)) {
                    this._tipoImpuestoField = value;
                    this.RaisePropertyChanged("_tipoImpuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _tipoPrecio {
            get {
                return this._tipoPrecioField;
            }
            set {
                if ((object.ReferenceEquals(this._tipoPrecioField, value) != true)) {
                    this._tipoPrecioField = value;
                    this.RaisePropertyChanged("_tipoPrecio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal _totalVenta {
            get {
                return this._totalVentaField;
            }
            set {
                if ((this._totalVentaField.Equals(value) != true)) {
                    this._totalVentaField = value;
                    this.RaisePropertyChanged("_totalVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _unidadMedida {
            get {
                return this._unidadMedidaField;
            }
            set {
                if ((object.ReferenceEquals(this._unidadMedidaField, value) != true)) {
                    this._unidadMedidaField = value;
                    this.RaisePropertyChanged("_unidadMedida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _ventaDetalleGasolutionsId {
            get {
                return this._ventaDetalleGasolutionsIdField;
            }
            set {
                if ((this._ventaDetalleGasolutionsIdField.Equals(value) != true)) {
                    this._ventaDetalleGasolutionsIdField = value;
                    this.RaisePropertyChanged("_ventaDetalleGasolutionsId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _ventaGasolutionsId {
            get {
                return this._ventaGasolutionsIdField;
            }
            set {
                if ((this._ventaGasolutionsIdField.Equals(value) != true)) {
                    this._ventaGasolutionsIdField = value;
                    this.RaisePropertyChanged("_ventaGasolutionsId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Documento", Namespace="http://schemas.datacontract.org/2004/07/APU.Negocio")]
    [System.SerializableAttribute()]
    public partial class Documento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CantidadItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoNotaCreditoDebitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPrecioUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionAdquirenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoAfectadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaEmisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private APU.Negocio.WS_Gasolutions.Item[] ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoSustentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreAdquirenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoAdquirenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private APU.Negocio.WS_Gasolutions.Operacion[] OperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OtrosCargosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RucEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoDocumentoAdquirenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoAfectadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoMonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private APU.Negocio.WS_Gasolutions.Tributo[] TributoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private APU.Negocio.WS_Gasolutions.VentaGnv[] VentaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CantidadItem {
            get {
                return this.CantidadItemField;
            }
            set {
                if ((this.CantidadItemField.Equals(value) != true)) {
                    this.CantidadItemField = value;
                    this.RaisePropertyChanged("CantidadItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoNotaCreditoDebito {
            get {
                return this.CodigoNotaCreditoDebitoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoNotaCreditoDebitoField, value) != true)) {
                    this.CodigoNotaCreditoDebitoField = value;
                    this.RaisePropertyChanged("CodigoNotaCreditoDebito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPrecioUnitario {
            get {
                return this.CodigoPrecioUnitarioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPrecioUnitarioField, value) != true)) {
                    this.CodigoPrecioUnitarioField = value;
                    this.RaisePropertyChanged("CodigoPrecioUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionItem {
            get {
                return this.DescripcionItemField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionItemField, value) != true)) {
                    this.DescripcionItemField = value;
                    this.RaisePropertyChanged("DescripcionItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionAdquirente {
            get {
                return this.DireccionAdquirenteField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionAdquirenteField, value) != true)) {
                    this.DireccionAdquirenteField = value;
                    this.RaisePropertyChanged("DireccionAdquirente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentoAfectado {
            get {
                return this.DocumentoAfectadoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoAfectadoField, value) != true)) {
                    this.DocumentoAfectadoField = value;
                    this.RaisePropertyChanged("DocumentoAfectado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEmision {
            get {
                return this.FechaEmisionField;
            }
            set {
                if ((this.FechaEmisionField.Equals(value) != true)) {
                    this.FechaEmisionField = value;
                    this.RaisePropertyChanged("FechaEmision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APU.Negocio.WS_Gasolutions.Item[] Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoSustento {
            get {
                return this.MotivoSustentoField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoSustentoField, value) != true)) {
                    this.MotivoSustentoField = value;
                    this.RaisePropertyChanged("MotivoSustento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreAdquirente {
            get {
                return this.NombreAdquirenteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreAdquirenteField, value) != true)) {
                    this.NombreAdquirenteField = value;
                    this.RaisePropertyChanged("NombreAdquirente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numeracion {
            get {
                return this.NumeracionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeracionField, value) != true)) {
                    this.NumeracionField = value;
                    this.RaisePropertyChanged("Numeracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumentoAdquirente {
            get {
                return this.NumeroDocumentoAdquirenteField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoAdquirenteField, value) != true)) {
                    this.NumeroDocumentoAdquirenteField = value;
                    this.RaisePropertyChanged("NumeroDocumentoAdquirente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APU.Negocio.WS_Gasolutions.Operacion[] Operacion {
            get {
                return this.OperacionField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacionField, value) != true)) {
                    this.OperacionField = value;
                    this.RaisePropertyChanged("Operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OtrosCargos {
            get {
                return this.OtrosCargosField;
            }
            set {
                if ((this.OtrosCargosField.Equals(value) != true)) {
                    this.OtrosCargosField = value;
                    this.RaisePropertyChanged("OtrosCargos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioUnitario {
            get {
                return this.PrecioUnitarioField;
            }
            set {
                if ((this.PrecioUnitarioField.Equals(value) != true)) {
                    this.PrecioUnitarioField = value;
                    this.RaisePropertyChanged("PrecioUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RucEmisor {
            get {
                return this.RucEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.RucEmisorField, value) != true)) {
                    this.RucEmisorField = value;
                    this.RaisePropertyChanged("RucEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((this.TipoDocumentoField.Equals(value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoDocumentoAdquirente {
            get {
                return this.TipoDocumentoAdquirenteField;
            }
            set {
                if ((this.TipoDocumentoAdquirenteField.Equals(value) != true)) {
                    this.TipoDocumentoAdquirenteField = value;
                    this.RaisePropertyChanged("TipoDocumentoAdquirente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumentoAfectado {
            get {
                return this.TipoDocumentoAfectadoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoAfectadoField, value) != true)) {
                    this.TipoDocumentoAfectadoField = value;
                    this.RaisePropertyChanged("TipoDocumentoAfectado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoMoneda {
            get {
                return this.TipoMonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoMonedaField, value) != true)) {
                    this.TipoMonedaField = value;
                    this.RaisePropertyChanged("TipoMoneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalVenta {
            get {
                return this.TotalVentaField;
            }
            set {
                if ((this.TotalVentaField.Equals(value) != true)) {
                    this.TotalVentaField = value;
                    this.RaisePropertyChanged("TotalVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APU.Negocio.WS_Gasolutions.Tributo[] Tributo {
            get {
                return this.TributoField;
            }
            set {
                if ((object.ReferenceEquals(this.TributoField, value) != true)) {
                    this.TributoField = value;
                    this.RaisePropertyChanged("Tributo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadItem {
            get {
                return this.UnidadItemField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadItemField, value) != true)) {
                    this.UnidadItemField = value;
                    this.RaisePropertyChanged("UnidadItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APU.Negocio.WS_Gasolutions.VentaGnv[] Venta {
            get {
                return this.VentaField;
            }
            set {
                if ((object.ReferenceEquals(this.VentaField, value) != true)) {
                    this.VentaField = value;
                    this.RaisePropertyChanged("Venta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/APU.Negocio")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoProducto {
            get {
                return this.CodigoProductoField;
            }
            set {
                if ((this.CodigoProductoField.Equals(value) != true)) {
                    this.CodigoProductoField = value;
                    this.RaisePropertyChanged("CodigoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operacion", Namespace="http://schemas.datacontract.org/2004/07/APU.Negocio")]
    [System.SerializableAttribute()]
    public partial class Operacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoOperacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoOperacion {
            get {
                return this.TipoOperacionField;
            }
            set {
                if ((this.TipoOperacionField.Equals(value) != true)) {
                    this.TipoOperacionField = value;
                    this.RaisePropertyChanged("TipoOperacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tributo", Namespace="http://schemas.datacontract.org/2004/07/APU.Negocio")]
    [System.SerializableAttribute()]
    public partial class Tributo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoTributoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoTributo {
            get {
                return this.TipoTributoField;
            }
            set {
                if ((this.TipoTributoField.Equals(value) != true)) {
                    this.TipoTributoField = value;
                    this.RaisePropertyChanged("TipoTributo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VentaGnv", Namespace="http://schemas.datacontract.org/2004/07/APU.Negocio")]
    [System.SerializableAttribute()]
    public partial class VentaGnv : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CaraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaProximoMantenimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaRevisionCilindroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IslaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MangueraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaquinaRegistradoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReciboField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cara {
            get {
                return this.CaraField;
            }
            set {
                if ((this.CaraField.Equals(value) != true)) {
                    this.CaraField = value;
                    this.RaisePropertyChanged("Cara");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaHora {
            get {
                return this.FechaHoraField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaHoraField, value) != true)) {
                    this.FechaHoraField = value;
                    this.RaisePropertyChanged("FechaHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaProximoMantenimiento {
            get {
                return this.FechaProximoMantenimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaProximoMantenimientoField, value) != true)) {
                    this.FechaProximoMantenimientoField = value;
                    this.RaisePropertyChanged("FechaProximoMantenimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaRevisionCilindro {
            get {
                return this.FechaRevisionCilindroField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaRevisionCilindroField, value) != true)) {
                    this.FechaRevisionCilindroField = value;
                    this.RaisePropertyChanged("FechaRevisionCilindro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hora {
            get {
                return this.HoraField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraField, value) != true)) {
                    this.HoraField = value;
                    this.RaisePropertyChanged("Hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Isla {
            get {
                return this.IslaField;
            }
            set {
                if ((this.IslaField.Equals(value) != true)) {
                    this.IslaField = value;
                    this.RaisePropertyChanged("Isla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Manguera {
            get {
                return this.MangueraField;
            }
            set {
                if ((this.MangueraField.Equals(value) != true)) {
                    this.MangueraField = value;
                    this.RaisePropertyChanged("Manguera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaquinaRegistradora {
            get {
                return this.MaquinaRegistradoraField;
            }
            set {
                if ((object.ReferenceEquals(this.MaquinaRegistradoraField, value) != true)) {
                    this.MaquinaRegistradoraField = value;
                    this.RaisePropertyChanged("MaquinaRegistradora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Recibo {
            get {
                return this.ReciboField;
            }
            set {
                if ((this.ReciboField.Equals(value) != true)) {
                    this.ReciboField = value;
                    this.RaisePropertyChanged("Recibo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Turno {
            get {
                return this.TurnoField;
            }
            set {
                if ((this.TurnoField.Equals(value) != true)) {
                    this.TurnoField = value;
                    this.RaisePropertyChanged("Turno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Facturacion", Namespace="http://schemas.datacontract.org/2004/07/APU.Negocio")]
    [System.SerializableAttribute()]
    public partial class Facturacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SolicitudProcesadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorFirmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorResumenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SolicitudProcesada {
            get {
                return this.SolicitudProcesadaField;
            }
            set {
                if ((this.SolicitudProcesadaField.Equals(value) != true)) {
                    this.SolicitudProcesadaField = value;
                    this.RaisePropertyChanged("SolicitudProcesada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValorFirma {
            get {
                return this.ValorFirmaField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorFirmaField, value) != true)) {
                    this.ValorFirmaField = value;
                    this.RaisePropertyChanged("ValorFirma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValorResumen {
            get {
                return this.ValorResumenField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorResumenField, value) != true)) {
                    this.ValorResumenField = value;
                    this.RaisePropertyChanged("ValorResumen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Gasolutions.IGasolutions")]
    public interface IGasolutions {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasolutions/VentaGasolutions_ListarCodigo", ReplyAction="http://tempuri.org/IGasolutions/VentaGasolutions_ListarCodigoResponse")]
        APU.Negocio.WS_Gasolutions.VentaGasolutionsInfo[] VentaGasolutions_ListarCodigo(int ventaGasolutionsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasolutions/VentaGasolutions_ListarCodigo", ReplyAction="http://tempuri.org/IGasolutions/VentaGasolutions_ListarCodigoResponse")]
        System.Threading.Tasks.Task<APU.Negocio.WS_Gasolutions.VentaGasolutionsInfo[]> VentaGasolutions_ListarCodigoAsync(int ventaGasolutionsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasolutions/VentaGasolutions_Insertar", ReplyAction="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarResponse")]
        int VentaGasolutions_Insertar(APU.Negocio.WS_Gasolutions.VentaGasolutionsInfo ventaPetroamericaInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasolutions/VentaGasolutions_Insertar", ReplyAction="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarResponse")]
        System.Threading.Tasks.Task<int> VentaGasolutions_InsertarAsync(APU.Negocio.WS_Gasolutions.VentaGasolutionsInfo ventaPetroamericaInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarLote", ReplyAction="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarLoteResponse")]
        int VentaGasolutions_InsertarLote(APU.Negocio.WS_Gasolutions.VentaGasolutionsInfo[] ventaPetroamericaInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarLote", ReplyAction="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarLoteResponse")]
        System.Threading.Tasks.Task<int> VentaGasolutions_InsertarLoteAsync(APU.Negocio.WS_Gasolutions.VentaGasolutionsInfo[] ventaPetroamericaInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarXml", ReplyAction="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarXmlResponse")]
        string VentaGasolutions_InsertarXml(string ventaXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarXml", ReplyAction="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarXmlResponse")]
        System.Threading.Tasks.Task<string> VentaGasolutions_InsertarXmlAsync(string ventaXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarGnvXml", ReplyAction="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarGnvXmlResponse")]
        string VentaGasolutions_InsertarGnvXml(string ventaXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarGnvXml", ReplyAction="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarGnvXmlResponse")]
        System.Threading.Tasks.Task<string> VentaGasolutions_InsertarGnvXmlAsync(string ventaXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasolutions/GenerarDocumento", ReplyAction="http://tempuri.org/IGasolutions/GenerarDocumentoResponse")]
        APU.Negocio.WS_Gasolutions.Facturacion GenerarDocumento(APU.Negocio.WS_Gasolutions.Documento documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasolutions/GenerarDocumento", ReplyAction="http://tempuri.org/IGasolutions/GenerarDocumentoResponse")]
        System.Threading.Tasks.Task<APU.Negocio.WS_Gasolutions.Facturacion> GenerarDocumentoAsync(APU.Negocio.WS_Gasolutions.Documento documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarNotaCreditoXml", ReplyAction="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarNotaCreditoXmlResponse")]
        string VentaGasolutions_InsertarNotaCreditoXml(string notaCreditoXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarNotaCreditoXml", ReplyAction="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarNotaCreditoXmlResponse")]
        System.Threading.Tasks.Task<string> VentaGasolutions_InsertarNotaCreditoXmlAsync(string notaCreditoXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarNotaDebitoXml", ReplyAction="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarNotaDebitoXmlResponse")]
        string VentaGasolutions_InsertarNotaDebitoXml(string notaDebitoXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarNotaDebitoXml", ReplyAction="http://tempuri.org/IGasolutions/VentaGasolutions_InsertarNotaDebitoXmlResponse")]
        System.Threading.Tasks.Task<string> VentaGasolutions_InsertarNotaDebitoXmlAsync(string notaDebitoXml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGasolutionsChannel : APU.Negocio.WS_Gasolutions.IGasolutions, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GasolutionsClient : System.ServiceModel.ClientBase<APU.Negocio.WS_Gasolutions.IGasolutions>, APU.Negocio.WS_Gasolutions.IGasolutions {
        
        public GasolutionsClient() {
        }
        
        public GasolutionsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GasolutionsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GasolutionsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GasolutionsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public APU.Negocio.WS_Gasolutions.VentaGasolutionsInfo[] VentaGasolutions_ListarCodigo(int ventaGasolutionsId) {
            return base.Channel.VentaGasolutions_ListarCodigo(ventaGasolutionsId);
        }
        
        public System.Threading.Tasks.Task<APU.Negocio.WS_Gasolutions.VentaGasolutionsInfo[]> VentaGasolutions_ListarCodigoAsync(int ventaGasolutionsId) {
            return base.Channel.VentaGasolutions_ListarCodigoAsync(ventaGasolutionsId);
        }
        
        public int VentaGasolutions_Insertar(APU.Negocio.WS_Gasolutions.VentaGasolutionsInfo ventaPetroamericaInfo) {
            return base.Channel.VentaGasolutions_Insertar(ventaPetroamericaInfo);
        }
        


        public System.Threading.Tasks.Task<int> VentaGasolutions_InsertarAsync(APU.Negocio.WS_Gasolutions.VentaGasolutionsInfo ventaPetroamericaInfo) {
            return base.Channel.VentaGasolutions_InsertarAsync(ventaPetroamericaInfo);
        }
        
        public int VentaGasolutions_InsertarLote(APU.Negocio.WS_Gasolutions.VentaGasolutionsInfo[] ventaPetroamericaInfo) {
            return base.Channel.VentaGasolutions_InsertarLote(ventaPetroamericaInfo);
        }
        
        public System.Threading.Tasks.Task<int> VentaGasolutions_InsertarLoteAsync(APU.Negocio.WS_Gasolutions.VentaGasolutionsInfo[] ventaPetroamericaInfo) {
            return base.Channel.VentaGasolutions_InsertarLoteAsync(ventaPetroamericaInfo);
        }
        
        public string VentaGasolutions_InsertarXml(string ventaXml) {
            return base.Channel.VentaGasolutions_InsertarXml(ventaXml);
        }
        
        public System.Threading.Tasks.Task<string> VentaGasolutions_InsertarXmlAsync(string ventaXml) {
            return base.Channel.VentaGasolutions_InsertarXmlAsync(ventaXml);
        }
        
        public string VentaGasolutions_InsertarGnvXml(string ventaXml) {
            return base.Channel.VentaGasolutions_InsertarGnvXml(ventaXml);
        }
        
        public System.Threading.Tasks.Task<string> VentaGasolutions_InsertarGnvXmlAsync(string ventaXml) {
            return base.Channel.VentaGasolutions_InsertarGnvXmlAsync(ventaXml);
        }
        
        public APU.Negocio.WS_Gasolutions.Facturacion GenerarDocumento(APU.Negocio.WS_Gasolutions.Documento documento) {
            return base.Channel.GenerarDocumento(documento);
        }
        
        public System.Threading.Tasks.Task<APU.Negocio.WS_Gasolutions.Facturacion> GenerarDocumentoAsync(APU.Negocio.WS_Gasolutions.Documento documento) {
            return base.Channel.GenerarDocumentoAsync(documento);
        }
        
        public string VentaGasolutions_InsertarNotaCreditoXml(string notaCreditoXml) {
            return base.Channel.VentaGasolutions_InsertarNotaCreditoXml(notaCreditoXml);
        }
        
        public System.Threading.Tasks.Task<string> VentaGasolutions_InsertarNotaCreditoXmlAsync(string notaCreditoXml) {
            return base.Channel.VentaGasolutions_InsertarNotaCreditoXmlAsync(notaCreditoXml);
        }
        
        public string VentaGasolutions_InsertarNotaDebitoXml(string notaDebitoXml) {
            return base.Channel.VentaGasolutions_InsertarNotaDebitoXml(notaDebitoXml);
        }
        
        public System.Threading.Tasks.Task<string> VentaGasolutions_InsertarNotaDebitoXmlAsync(string notaDebitoXml) {
            return base.Channel.VentaGasolutions_InsertarNotaDebitoXmlAsync(notaDebitoXml);
        }
    }
}
